language: ruby

before_install:
  # install evm
  - curl -fsSL https://raw.githubusercontent.com/rejeep/evm/master/go | bash
  - export PATH="$HOME/.evm/bin:$PATH"
  - evm config path /tmp

  # install emacs
  - evm install $EVM_EMACS --use --skip

before_script:
  - ruby --version
  - rake --version
  - emacs --version

script:
  - rake compilation_test

env:
  - EVM_EMACS=emacs-24.5-travis
  - EVM_EMACS=emacs-25.3-travis
  - EVM_EMACS=emacs-26.1-travis
